/** Static list of Turkish and major European exchange universities */
export const UNIVERSITIES = [
  // Türkiye - İstanbul
  'Boğaziçi Üniversitesi',
  'İstanbul Teknik Üniversitesi (İTÜ)',
  'İstanbul Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Marmara Üniversitesi',
  'Galatasaray Üniversitesi',
  'Koç Üniversitesi',
  'Sabancı Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Bilgi Üniversitesi',
  'Özyeğin Üniversitesi',
  'Medipol Üniversitesi',
  'Yeditepe Üniversitesi',
  'Kadir Has Üniversitesi',
  'Maltepe Üniversitesi',
  'Beykent Üniversitesi',
  'Işık Üniversitesi',
  // Türkiye - Ankara
  'Orta Doğu Teknik Üniversitesi (ODTÜ)',
  'Hacettepe Üniversitesi',
  'Ankara Üniversitesi',
  'Bilkent Üniversitesi',
  'TOBB Ekonomi ve Teknoloji Üniversitesi',
  'Çankaya Üniversitesi',
  'Başkent Üniversitesi',
  'Gazi Üniversitesi',
  // Türkiye - İzmir
  'Ege Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü (İYTE)',
  'İzmir Ekonomi Üniversitesi',
  'Yaşar Üniversitesi',
  // Türkiye - Diğer
  'Uludağ Üniversitesi',
  'Anadolu Üniversitesi',
  'Akdeniz Üniversitesi',
  'Çukurova Üniversitesi',
  'Erciyes Üniversitesi',
  'Selçuk Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Atatürk Üniversitesi',
  'Pamukkale Üniversitesi',
  'Mersin Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  // Avrupa - Popüler Erasmus Destinasyonları
  'Sorbonne University',
  'Sciences Po Paris',
  'University of Amsterdam',
  'Vrije Universiteit Amsterdam',
  'Technical University of Munich (TUM)',
  'Humboldt University of Berlin',
  'Freie Universität Berlin',
  'University of Barcelona',
  'Universitat Politècnica de Catalunya',
  'Sapienza University of Rome',
  'Politecnico di Milano',
  'University of Lisbon',
  'University of Porto',
  'Charles University Prague',
  'Czech Technical University Prague',
  'University of Vienna',
  'Warsaw University',
  'Jagiellonian University Krakow',
  'University of Copenhagen',
  'KTH Royal Institute of Technology Stockholm',
  'University of Helsinki',
  'University of Oslo',
  'KU Leuven',
  'ETH Zürich',
  'University of Edinburgh',
  'University College London (UCL)',
  'Trinity College Dublin',
] as const;

export type UniversityName = typeof UNIVERSITIES[number];
